language: python
python:
   - "2.7"
   - "3.4"
services:
   - mysql
   - postgresql
before_install:
   - "sudo apt-get install -y libmysqlclient-dev libpq-dev"
   - "mysqladmin create test"
env:
   global:
      - MYSQL_HOST=localhost
      - PGHOST=localhost
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=
install: "pip install -r requirements.txt"
script:
   - "nosetests --with-coverage --cover-package=healthcheck"
after_success:
   - coveralls
